In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
## Lets load the Boston house pricing datasets

In [3]:
from sklearn.datasets import fetch_california_housing

In [4]:
house_df = fetch_california_housing()

In [5]:
house_df.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [6]:
## Lets check the description of the datasets

In [7]:
print(house_df.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33 (1997) 291-297

In [8]:
print(house_df.data)

[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]

In [9]:
print(house_df.target)

[4.526 3.585 3.521 ... 0.923 0.847 0.894]

In [10]:
print(house_df.feature_names)

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

## Preparing the dataset

In [11]:
dataset = pd.DataFrame(house_df.data, columns=house_df.feature_names)

In [12]:
dataset.head(2)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.02381,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.97188,2401.0,2.109842,37.86,-122.22

In [13]:
dataset['price']=house_df.target

In [14]:
dataset.head(2)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,price
0,8.3252,41.0,6.984127,1.02381,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.97188,2401.0,2.109842,37.86,-122.22,3.585

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   price       20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [16]:
dataset.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,price
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

## missing values

In [17]:
dataset.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
price         0
dtype: int64

## Exploratory data analysis

## correlation
it is very imp to check the correlation of the independent variables wrt regression problems to find how my independent features are related to target variable. If they are highly positively correlated or highly negatively correlated that indicates our model performance will be high

In [18]:
dataset.corr()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,price
MedInc,1.000000,-0.119034,0.326895,-0.062040,0.004834,0.018766,-0.079809,-0.015176,0.688075
HouseAge,-0.119034,1.000000,-0.153277,-0.077747,-0.296244,0.013191,0.011173,-0.108197,0.105623
AveRooms,0.326895,-0.153277,1.000000,0.847621,-0.072213,-0.004852,0.106389,-0.027540,0.151948
AveBedrms,-0.062040,-0.077747,0.847621,1.000000,-0.066197,-0.006181,0.069721,0.013344,-0.046701
Population,0.004834,-0.296244,-0.072213,-0.066197,1.000000,0.069863,-0.108785,0.099773,-0.024650
AveOccup,0.018766,0.013191,-0.004852,-0.006181,0.069863,1.000000,0.002366,0.002476,-0.023737
Latitude,-0.079809,0.011173,0.106389,0.069721,-0.108785,0.002366,1.000000,-0.924664,-0.144160
Longitude,-0.015176,-0.108197,-0.027540,0.013344,0.099773,0.002476,-0.924664,1.000000,-0.045967
price,0.688075,0.105623,0.151948,-0.046701,-0.024650,-0.023737,-0.144160,-0.045967,1.000000

Multi colinarity: if 2 independent features are highly correlated then we drop one of the feature and just keep one.
We mainly need to oberve the correlation btw independent to dependent and btw indendent features

In [ ]:
import seaborn as sns
sns.pairplot(dataset)

In [ ]:
plt.scatter(dataset['MedInc'], dataset['price'])
plt.xlabel('MedInc')
plt.ylabel('Price')

In [ ]:
sns.regplot(x='MedInc',y='price',data=dataset)

In [ ]:
sns.regplot(x='AveRooms',y='price',data=dataset)

## Independent and dependent features

In [ ]:
dataset.head(2)

In [ ]:
x = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.3, random_state=19)

Standard scalar: Our main goal in linear regresion is that we reach near or to global minimum. all the different features in our datasets are calculated based on different units and we use gradeint descent to reach gobal minimum point but if points are of different units it will take a lot of time to reach that. so thats why we scale the data before we use it

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
x_train=scaler.fit_transform(x_train)

In [ ]:
# we just use the fit instead of fit_transform for test data, bcoz we just want to apply the same transformation that we did for train dataset, to make sure thatmy model doesnot know much about my test dat
x_test = scaler.transform(x_test)

In [ ]:
print(x_test)

## model training

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(x_train,y_train)

In [ ]:
## print coefficients and the other is intercept
lr.coef_

In [ ]:
print(lr.intercept_)

In [ ]:
## on which parameters model has been trained
lr.get_params()

In [ ]:
## Prediction with test data
reg_pred=lr.predict(x_test)

In [ ]:
reg_pred

In [ ]:
## plot a scatter plot for pred
plt.scatter(reg_pred,y_test)

In [ ]:
residuals = reg_pred - y_test # error btw pred and y_test

In [ ]:
## plot this residuals

sns.displot(residuals,kind='kde')

## performance metrics

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

print(mean_absolute_error(reg_pred,y_test))
print(mean_squared_error(reg_pred,y_test))
print(np.sqrt(mean_squared_error(reg_pred,y_test)))

## r square and adjusted r square

In [ ]:
from sklearn.metrics import r2_score
score = r2_score(y_test, reg_pred)
print(score)

In [ ]:
house_df.data[0]

In [ ]:
house_df.data[0].reshape(1,-1)

In [ ]:
lr.predict(scaler.transform(house_df.data[0].reshape(1,-1)))

In [ ]:
house_df.target[0]

## Pickle the model file for deployment

In [ ]:
import pickle
pickle.dump(lr,open('./regmodel.pkl','wb'))

In [ ]:
pickled_model=pickle.load(open('./regmodel.pkl', 'rb'))

In [ ]:
pickled_model.predict(scaler.transform(house_df.data[0].reshape(1,-1)))